platform :ios, '8.0'
inhibit_all_warnings!

target 'QCNOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QCNOS
    
	pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
	pod 'MJRefresh'
	pod 'AFNetworking', '~> 3.1.0'
	pod 'SDWebImage', '~> 3.8.2'
	pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'YYModel'
    pod 'Realm'

end

